routes/web.php
<?php

use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return redirect()->route('login');
// });

Route::get('/', 'Frontend\PageController@landing')->name('landing');
Route::get('/about', 'Frontend\PageController@pageAbout')->name('page.about');
Route::get('/service', 'Frontend\PageController@pageService')->name('page.service');
Route::get('/register-bank-account', 'Frontend\PageController@pageBankAccount')->name('page.account');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/account/profile', 'ProfileController@show')->name('profile.show');
Route::put('/account/profile', 'ProfileController@update')->name('profile.update');
Route::put('/account/profile/member', 'ProfileController@updateMember')->name('profile.update.member');

Route::group(['prefix' => 'dash', 'middleware' => ['auth', 'role:admin']], function () {
    Route::get('user', 'Backend\UserController@index' )->name('user.index');
    Route::post('user', 'Backend\UserController@store' )->name('user.store');
    Route::get('user/create', 'Backend\UserController@create' )->name('user.create');
    Route::get('user/{id}/edit', 'Backend\UserController@edit' )->name('user.edit');
    Route::put('user/{id}/update', 'Backend\UserController@update' )->name('user.update');
    Route::delete('user/{id}', 'Backend\UserController@destroy' )->name('user.destroy');
    
    Route::resource('report', 'Backend\ReportController');
});

Route::group(['prefix' => 'dash', 'middleware' => ['auth', 'role:admin|user']], function () {
    Route::get('submission/{id}/verification', 'Backend\SubmissionController@verification' )->name('submission.verification');
    Route::patch('submission/{id}/verification', 'Backend\SubmissionController@verificationStore' )->name('submission.verification.store');

    Route::get('borrow/{id}/verification', 'Backend\BorrowController@verification' )->name('borrow.verification');
    Route::patch('borrow/{id}/verification', 'Backend\BorrowController@verificationStore' )->name('borrow.verification.store');
    Route::patch('borrow/return', 'Backend\BorrowController@returnStore' )->name('borrow.return.store');

    Route::resource('borrow', 'Backend\BorrowController');
    Route::resource('submission', 'Backend\SubmissionController');
    Route::resource('asset', 'Backend\AssetController');
});

app/Asset.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Asset extends Model
{
    protected $appends = ['display_status', 'display_purchase_date', 'display_expire_date'];

    public function user()
    {
        return $this->belongsTo('App\User', 'user_id');
    }
    
    public function borrow()
    {
        return $this->hasOne('App\Borrow', 'asset_id')->whereNull('return_date');
    }

    public function getDisplayPurchaseDateAttribute()
    {
        $date = $this->purchase_date;
        return date_dmy($date);
    }

    public function getDisplayExpireDateAttribute()
    {
        $date = $this->expire_date;
        return date_dmy($date);
    }

    public function getDisplayStatusAttribute()
    {
        $result = '';
        $status = $this->status;

        switch ($status) {
            case '100':
                $result = 'Tersedia';
                break;
            case '200':
                $result = 'Dipinjam';
                break;
            
            default:
                $result = 'Tidak Ada';
                break;
        }

        return $result;
    }
}

app/Http/Controllers/Backend/AssetController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Yajra\Datatables\Datatables;
use Session;
use App\Asset;
use App\AssetSubmission;


class AssetController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if ($request->ajax()) {

            $assets = Asset::with('user');

            if ($request->get('status') != null) {
                if ($request->status != 'all') {
                    $assets->whereStatus($request->status);
                }
            }

            $assets = $assets->select('assets.*');

            return Datatables::of($assets)
                ->addIndexColumn()
                ->addColumn('action', function ($asset) {
                    return view('partials._action', [
                        'model'           => $asset,
                        // 'form_url'        => route('asset.destroy', $asset->id),
                        // 'edit_url'        => route('asset.edit', $asset->id),
                        'show_url'        => route('asset.show', $asset->id),
                    ]);
                })
                ->escapeColumns([])
                ->make(true);
        }

        return view('backend.assets.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $asset = Asset::find($id);
        $types = config('static.type');

        return view('backend.assets.show')->with(compact('types', 'asset'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Backend/BorrowController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Yajra\Datatables\Datatables;
use Session;
use App\Borrow;
use App\Asset;
use App\AssetSubmission;
use Illuminate\Support\Facades\Auth;

class BorrowController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if ($request->ajax()) {

            $user = Auth::user();

            $borrows = Borrow::with('user', 'asset');

            if ($request->get('status') != null) {
                if ($request->status != 'all') {
                    $borrows->whereStatus($request->status);
                }
            }

            if ($user->role == 'user') {
                $borrows->where('user_id', $user->id);
            }

            $borrows = $borrows->select('borrows.*');

            return Datatables::of($borrows)
                ->addIndexColumn()
                ->addColumn('action', function ($borrow) {
                    return view('partials._action', [
                        'model'           => $borrow,
                        // 'form_url'        => route('borrow.destroy', $borrow->id),
                        // 'edit_url'        => route('borrow.edit', $borrow->id),
                        'show_url'        => route('borrow.show', $borrow->id),
                        'verif_url'       => route('borrow.verification', $borrow->id),
                        'return_url'      => true,
                        'cond'            => true,
                    ]);
                })
                ->escapeColumns([])
                ->make(true);
        }

        return view('backend.borrows.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $assets = Asset::where('status', 100)->get();

        return view('backend.borrows.create')->with(compact('assets'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'asset_id' => 'required|numeric',
        ]);

        $asset_id = $request->asset_id;
        $user_id = Auth::user()->id;

        $model = new Borrow();
        $model->asset_id = $asset_id;
        $model->user_id = $user_id;
        $model->borrow_date = date('Y-m-d');
        $model->status = 100;
        $model->save();

        Session::flash("flash_notification", [
            "level" => "success",
            "message" => "Aset $model->name berhasil diajukan"
        ]);

        return redirect()->route('borrow.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $borrow = Borrow::with('user', 'asset')->find($id);
        $types = config('static.type');

        return view('backend.borrows.show')->with(compact('borrow', 'types'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    public function verification($id)
    {
        $borrow = Borrow::with('user', 'asset')->find($id);
        $types = config('static.type');

        return view('backend.borrows.verification')->with(compact('types', 'borrow'));
    }

    public function verificationStore(Request $request, $id)
    {
        $this->validate($request, [
            'status' => 'required|numeric',
        ]);

        $status = $request->status;

        $model = Borrow::find($id);
        $model->status = $status;
        $model->save();

        if ($status == 200) {
            $asset = Asset::find($model->asset_id);
            $asset->status = 200;
            $asset->save();
        }

        Session::flash("flash_notification", [
            "level" => "success",
            "message" => "Peminjaman aset berhasil diverifikasi"
        ]);

        return redirect()->route('borrow.index');
    }

    public function returnStore(Request $request)
    {
        $this->validate($request, [
            'borrow_id' => 'required|numeric',
        ]);

        $borrow_id = $request->borrow_id;

        $model = Borrow::find($borrow_id);
        $model->status = 300;
        $model->return_date = date('Y-m-d');
        $model->save();

        $asset = Asset::find($model->asset_id);
        $asset->status = 100;
        $asset->save();

        Session::flash("flash_notification", [
            "level" => "success",
            "message" => "Aset $asset->name berhasil dikembalikan"
        ]);

        return redirect()->route('borrow.index');
    }
}

app/Http/Controllers/Backend/ReportController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class ReportController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('backend.reports.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/backend/assets/index.blade.php
@extends('layouts.main')

@section('content')
  <section class="section">
    <div class="section-header">
      <h1>Pengajuan Aset</h1>
    </div>

    <div class="d-sm-flex align-items-center justify-content-start mb-4">
        {{-- <a class="btn btn-sm btn-primary" href="{{ route('submission.create') }}"><i class="fa fa-plus"></i> Buat Pengajuan</a> --}}
      {{-- <div class="form-inline ml-auto">
        <label>Filter Status</label>
        <select name="status" class="form-control-sm">
          <option value="all">Semua</option>
          <option value="100">Menunggu Pesetujuan</option>
          <option value="200">Disetujui</option>
          <option value="10">Ditolak</option>
        </select>
        <button class="btn btn-sm btn-primary ml-2" id="btn-filter"><i class="fas fa-filter"></i></button>
      </div> --}}
    </div>

    <div class="row">
      <div class="col-lg-12">

        <!-- Basic Card Example -->
        <div class="card card-primary">
          <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold">List Aset</h6>
          </div>
          <div class="card-body">

          <div class="table-responsive">
            <table class="table table-striped datatable">
              <thead>                                 
                <tr>
                  <th>#</th>
                  <th>Kode</th>
                  <th>Nama</th>
                  <th>Jenis</th>
                  <th>Tanggal Beli</th>
                  <th>Tanggal Layak</th>
                  <th>Harga</th>
                  <th>Keterangan</th>
                  <th>Status</th>
                  <th>Aksi</th>
                </tr>
              </thead>
              <tbody></tbody>
            </table>
          </div>

          </div>
        </div>
      </div>
    </div>
  </section>
@endsection
@section('script')
<script>
  $(document).ready(function() {
      $('.datatable').DataTable({
          processing: true,
          serverSide: true,
          autoWidth: false,
          language: {
              url: '{{ asset('assets/stisla/modules/datatables/lang/Indonesian.json') }}'
          },
          ajax: {
            url: '{{ route('asset.index') }}',
            data: function (d) {
              d.status = $('select[name=status]').val()
            }
          },
          columns: [
            {data: 'DT_RowIndex', name: 'DT_RowIndex', orderable: false, searchable: false},
            {data: 'code', name: 'code'},
            {data: 'name', name: 'name'},
            {data: 'type', name: 'type'},
            {data: 'display_purchase_date', name: 'purchase_date'},
            {data: 'display_expire_date', name: 'expire_date'},
            {data: null, name: 'price', render: function ( data, type, row ) {
              return 'Rp ' + numberFormat(parseInt(data.price));
            }},
            {data: 'description', name: 'description'},
            {data: 'display_status', name: 'display_status'},
            {data: 'action', name: 'action', orderable: false, searchable: false},
          ]
      });

      $('#btn-filter').click(function(){
         $('.datatable').DataTable().draw(true);
      });

      $(document).on('click','.js-submit-confirm', function(e){
          e.preventDefault();
          swal({
            title: 'Apakah anda yakin ingin menghapus?',
            text: 'Data yang sudah dihapus, tidak dapat dikembalikan!',
            icon: 'warning',
            buttons: true,
            dangerMode: true,
          })
          .then((willDelete) => {
            if (willDelete) {
              $(this).closest('form').submit();
            } 
          });
      });
  });

  function numberFormat(x) {
    return x.toString().replace(/\B(?<!\.\d*)(?=(\d{3})+(?!\d))/g, ".");
  }

  const capitalize = (s) => {
    if (typeof s !== 'string') return ''
    return s.charAt(0).toUpperCase() + s.slice(1)
  }
</script>
@endsection

resources/views/backend/assets/show.blade.php
@extends('layouts.main')

@section('content')
  <section class="section">
    <div class="section-header">
      <h1>Detail Aset</h1>
    </div>

    <form method="POST" action="{{ route('asset.update', $asset->id) }}" enctype="multipart/form-data">
      <div class="row">
        <div class="col-lg-12">
          <div class="card card-primary">
            <div class="card-header py-3">
              <h6 class="m-0 font-weight-bold">Informasi Aset</h6>
            </div>
            <div class="card-body">
              {{ csrf_field() }}
              @method('PUT')

              <div class="row">
                <div class="form-group col-6 {{ $errors->has('name') ? ' has-error' : '' }}">
                  <label for="name">Nama Aset</label>
                  <input id="name" type="text" class="form-control @if ($errors->has('name')) is-invalid @endif" name="name" tabindex="1" value="{{ $asset->name }}" disabled>
                  @if ($errors->has('name'))
                    <div class="invalid-feedback">
                      {{ $errors->first('name') }}
                    </div>
                  @endif
                </div>
                
                <div class="form-group col-6 {{ $errors->has('type') ? ' has-error' : '' }}">
                    <label for="type">Jenis Aset</label>
                    <select name="type" class="form-control select2 @if ($errors->has('type')) is-invalid @endif" data-placeholder="Pilih Jenis Aset" disabled>
                      <option value=""></option>
                      @foreach ($types as $item)
                        <option value="{{ $item }}" @if ($asset->type == $item) selected @endif>{{ $item }}</option>
                      @endforeach
                    </select>
                    @if ($errors->has('type'))
                      <div class="invalid-feedback">
                        {{ $errors->first('type') }}
                      </div>
                    @endif
                  </div>
              </div>

              <div class="row">
                <div class="form-group col-6 {{ $errors->has('year') ? ' has-error' : '' }}">
                  <label for="year">Tahun Anggaran</label>
                  <input id="year" type="number" min="1900" max="2099" class="form-control @if ($errors->has('year')) is-invalid @endif" name="year" tabindex="1" value="{{ $asset->year }}" disabled>
                  @if ($errors->has('year'))
                    <div class="invalid-feedback">
                      {{ $errors->first('year') }}
                    </div>
                  @endif
                </div>

                <div class="form-group col-6 {{ $errors->has('price') ? ' has-error' : '' }}">
                  <label for="price">Harga Aset</label>
                  <input id="price" type="text" class="form-control @if ($errors->has('price')) is-invalid @endif" name="price" tabindex="1" value="{{ rupiah($asset->price) }}" disabled>
                  @if ($errors->has('price'))
                    <div class="invalid-feedback">
                      {{ $errors->first('price') }}
                    </div>
                  @endif
                </div>
              </div>

              <div class="row">
                <div class="form-group col-6 {{ $errors->has('purchase_date') ? ' has-error' : '' }}">
                  <label for="purchase_date">Tanggal Beli Aset</label>
                  <input id="purchase_date" type="date" class="form-control @if ($errors->has('purchase_date')) is-invalid @endif" name="purchase_date" tabindex="1" value="{{ $asset->purchase_date }}" disabled>
                  @if ($errors->has('purchase_date'))
                    <div class="invalid-feedback">
                      {{ $errors->first('purchase_date') }}
                    </div>
                  @endif
                </div>

                <div class="form-group col-6 {{ $errors->has('expire_date') ? ' has-error' : '' }}">
                  <label for="expire_date">Tanggal Layak Aset</label>
                  <input id="expire_date" type="date" class="form-control @if ($errors->has('expire_date')) is-invalid @endif" name="expire_date" tabindex="1" value="{{ $asset->expire_date }}" disabled>
                  @if ($errors->has('expire_date'))
                    <div class="invalid-feedback">
                      {{ $errors->first('expire_date') }}
                    </div>
                  @endif
                </div>
              </div>

              <div class="form-group {{ $errors->has('description') ? ' has-error' : '' }}">
                <label for="description">Keterangan</label>
                <textarea name="description" id="description" class="form-control @if ($errors->has('description')) is-invalid @endif" disabled>{{ $asset->description }}</textarea>
                @if ($errors->has('description'))
                  <div class="invalid-feedback">
                    {{ $errors->first('description') }}
                  </div>
                @endif
              </div>
              
            </div>
          </div>
        </div>
      </div>
    </form>
  </section>
@endsection

@section('script')
  <script>
    $(document).ready(function () {
      bsCustomFileInput.init()
      $('.select2').select2();
    })
  </script>
@endsection